# Server
source: docs
destination: _gh_pages

# Custom vars
repo: https://github.com/vsn4ik/bootstrap-submenu
description: Bootstrap Sub-Menus.

download:
  dist: https://github.com/vsn4ik/bootstrap-submenu/releases/download/v1.2.12/bootstrap-submenu-1.2.12-dist.zip
