# Server
source: docs
destination: _gh_pages

# Custom vars
repo: https://github.com/vsn4ik/bootstrap-submenu
description: Bootstrap Sub-Menus.

jquery_path: http://code.jquery.com/jquery-2.1.1
bootstrap_path: http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1
